plugins {
    id 'com.android.application'
}

android {
    namespace 'com.drok.exam2doc'
    compileSdk 34

    defaultConfig {
        applicationId "com.drok.exam2doc"
        minSdk 29
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }

    signingConfigs {
        release {
            storeFile file("../../keystore/exam2doc.jks")
            storePassword "exam2doc2026"
            keyAlias "exam2doc"
            keyPassword "exam2doc2026"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    buildFeatures {
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
